# Modified: Friday, November 9, 2018 7:16 PM

version: '3.5'

networks:
  proxy:
    external: true

services:

  portainer:
    image: portainer/portainer
    container_name: "portainer"
    command: -H unix:///var/run/docker.sock
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - proxy
    labels:
      - traefik.backend=portainer
      - traefik.port=9000
      - "traefik.frontend.rule=Host:static.grinnell.edu;PathPrefixStrip:/portainer"
      - traefik.docker.network=proxy
      
